/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java_assignment;

import javax.swing.*;
import java.io.*;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Danish
 */
public class Admin_function extends javax.swing.JFrame {
    
    private RegistrationCustomer Register  ;
    private RegistrationVendor Register1 ;
    private RegistrationDelivery Register2;
    /**
     * Creates new form Register_Customer
     */
    
            
    public Admin_function() {
        initComponents();
        Register = new RegistrationCustomer("","","","",0);
        txtCredit.setText("0.0");// set a default value for txtCredit
        Register.setCustomerCredit(0.0);
        Register1 = new RegistrationVendor("","","","");
        Register2 =new RegistrationDelivery("","","","");
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jOptionPane2 = new javax.swing.JOptionPane();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtID1 = new javax.swing.JTextField();
        txtPassword1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtName1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtContact1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnGoLO = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCredit = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        btnGoLO1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtName2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtContact2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtPassword2 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        btnGoLO2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtName3 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtContact3 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtPassword3 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        btnGoLO3 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtID4 = new javax.swing.JTextField();
        txtPassword4 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txtName4 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtContact4 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        btnGoLO4 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 859, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setText("Identification(ID):");

        jLabel8.setText("Password:");

        jButton3.setText("Register");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel9.setText("Name:");

        jLabel10.setText("Contact Number:");

        txtContact1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContact1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Register Account for Vendor");

        btnGoLO.setText("Logout");
        btnGoLO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoLOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jButton3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtID1)
                            .addComponent(txtPassword1)
                            .addComponent(txtName1)
                            .addComponent(txtContact1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGoLO)))
                .addContainerGap(712, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnGoLO, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtContact1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jButton3)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Register Vendor", jPanel2);

        jLabel1.setText("Identification(ID):");

        jLabel2.setText("Password:");

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Name:");

        jLabel5.setText("Contact Number:");

        txtContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactActionPerformed(evt);
            }
        });

        jLabel3.setText("Credit:");

        txtCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreditActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setText("Register Account for Customer");

        btnGoLO1.setText("Logout");
        btnGoLO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoLO1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(txtPassword)
                            .addComponent(txtName)
                            .addComponent(txtContact)
                            .addComponent(txtCredit)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnGoLO1)))
                .addContainerGap(736, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnGoLO1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Register Customer", jPanel1);

        jLabel11.setText("Name:");

        jButton5.setText("Update Vendor");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel13.setText("Contact Number:");

        jLabel14.setText("Password:");

        txtPassword2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassword2ActionPerformed(evt);
            }
        });

        jButton6.setText("Load ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Vendor ID", "Name", "Contact Number", "Password"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton11.setText("Delete");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel22.setText("Update Vendor Profile");

        btnGoLO2.setText("Logout");
        btnGoLO2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoLO2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(224, 224, 224))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName2)
                                    .addComponent(txtContact2)
                                    .addComponent(txtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGoLO2)))
                        .addGap(41, 41, 41)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(346, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtContact2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGoLO2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Update Vendor Profile", jPanel5);

        jLabel12.setText("Name:");

        jButton7.setText("Update Customer");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel15.setText("Contact Number:");

        jLabel16.setText("Password:");

        txtPassword3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassword3ActionPerformed(evt);
            }
        });

        jButton8.setText("Load ");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Customer ID", "Name", "Contact Number", "Password"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton12.setText("Topup Credit");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Delete");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel23.setText("Update Customer Profile");

        btnGoLO3.setText("Logout");
        btnGoLO3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoLO3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(233, 233, 233)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton7)
                                    .addComponent(jButton13)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName3)
                                    .addComponent(txtContact3)
                                    .addComponent(txtPassword3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jButton12)))
                        .addGap(117, 117, 117))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnGoLO3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(346, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(txtName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(txtContact3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(txtPassword3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnGoLO3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Update Customer Profile", jPanel7);

        jLabel17.setText("Identification(ID):");

        jLabel18.setText("Password:");

        jButton4.setText("Register");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel19.setText("Name:");

        jLabel20.setText("Contact Number:");

        txtContact4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContact4ActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Delivery Runner ID", "Name", "Contact Number", "Passoword"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton9.setText("Load");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Delete");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel24.setText("Manage Account for Delivery Runner");

        btnGoLO4.setText("Logout");
        btnGoLO4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoLO4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton4)
                                .addComponent(txtID4, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                .addComponent(txtPassword4)
                                .addComponent(txtName4)
                                .addComponent(txtContact4))
                            .addComponent(jButton10)
                            .addComponent(jButton2)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(btnGoLO4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton9)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnGoLO4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtID4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtName4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtContact4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtPassword4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 566, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Delivery Runner", jPanel9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel)jTable2.getModel();

        //set data text field when raw
        String name = tblModel.getValueAt(jTable2.getSelectedRow(), 1).toString();
        String contact = tblModel.getValueAt(jTable2.getSelectedRow(), 2).toString();
        String password = tblModel.getValueAt(jTable2.getSelectedRow(), 3).toString();

        //set to textfield
        txtName3.setText(name);
        txtContact3.setText(contact);
        txtPassword3.setText(password);
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        displayCustomerDataInTable();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void txtPassword3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassword3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassword3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = jTable2.getSelectedRow();

        if (selectedRowIndex == -1) {
            jOptionPane1.showMessageDialog(Admin_function.this, "Please select a row to update.");
            return;
        }

        // Get the data from the selected row
        String id = jTable2.getValueAt(selectedRowIndex, 0).toString();
        String newName = txtName3.getText();
        String newContact = txtContact3.getText();
        String newPassword = txtPassword3.getText();

        // Read the existing content of the file
        ArrayList<String> lines = new ArrayList<>();
        try (BufferedReader br = new BufferedReader(new FileReader("CustomerData.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                lines.add(line);
            }
        } catch (IOException e) {
            e.printStackTrace();
            jOptionPane1.showMessageDialog(Admin_function.this, "Error reading from file: " + e.getMessage(), "Error", jOptionPane1.ERROR_MESSAGE);
            return;
        }

        // Update the selected row's data
        String updatedRow = id + "," + newName + "," + newContact + "," + newPassword;
        lines.set(selectedRowIndex, updatedRow);

        // Write the modified content back to the file
        try (BufferedWriter bw = new BufferedWriter(new FileWriter("CustomerData.txt"))) {
            for (String line : lines) {
                bw.write(line);
                bw.newLine();
            }
            jOptionPane1.showMessageDialog(Admin_function.this, "Customer information updated successfully!");
        } catch (IOException e) {
            e.printStackTrace();
            jOptionPane1.showMessageDialog(Admin_function.this, "Error writing to file: " + e.getMessage(), "Error", jOptionPane1.ERROR_MESSAGE);
        }

        // Clear text fields after updating
        clearTextFields();
        // Refresh the table with updated data
        displayCustomerDataInTable();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();

        //set data text field when raw
        String name = tblModel.getValueAt(jTable1.getSelectedRow(), 1).toString();
        String contact = tblModel.getValueAt(jTable1.getSelectedRow(), 2).toString();
        String password = tblModel.getValueAt(jTable1.getSelectedRow(), 3).toString();

        //set to textfield
        txtName2.setText(name);
        txtContact2.setText(contact);
        txtPassword2.setText(password);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        displayVendorDataInTable();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtPassword2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassword2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassword2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = jTable1.getSelectedRow();

        if (selectedRowIndex == -1) {
            jOptionPane1.showMessageDialog(Admin_function.this, "Please select a row to update.");
            return;
        }

        // Get the data from the selected row
        String id = jTable1.getValueAt(selectedRowIndex, 0).toString();
        String newName = txtName2.getText();
        String newContact = txtContact2.getText();
        String newPassword = txtPassword2.getText();

        // Read the existing content of the file
        ArrayList<String> lines = new ArrayList<>();
        try (BufferedReader br = new BufferedReader(new FileReader("Vendor.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                lines.add(line);
            }
        } catch (IOException e) {
            e.printStackTrace();
            jOptionPane1.showMessageDialog(Admin_function.this, "Error reading from file: " + e.getMessage(), "Error", jOptionPane1.ERROR_MESSAGE);
            return;
        }

        // Update the selected row's data
        String updatedRow = id + "," + newName + "," + newContact + "," + newPassword;
        lines.set(selectedRowIndex, updatedRow);

        // Write the modified content back to the file
        try (BufferedWriter bw = new BufferedWriter(new FileWriter("Vendor.txt"))) {
            for (String line : lines) {
                bw.write(line);
                bw.newLine();
            }
            jOptionPane1.showMessageDialog(Admin_function.this, "Vendor information updated successfully!");
        } catch (IOException e) {
            e.printStackTrace();
            jOptionPane1.showMessageDialog(Admin_function.this, "Error writing to file: " + e.getMessage(), "Error", jOptionPane1.ERROR_MESSAGE);
        }

        // Clear text fields after updating
        clearTextFields();
        // Refresh the table with updated data
        displayVendorDataInTable();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreditActionPerformed

    private void txtContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String id = txtID.getText();
        String Name = txtName.getText();
        String Contact = txtContact.getText();
        String Password = txtPassword.getText();
        
        // Check if any text fields is empty
        if (id.isEmpty() || Name.isEmpty() || Contact.isEmpty() || Password.isEmpty()) {
        jOptionPane1.showMessageDialog(Admin_function.this, "Please fill in all fields.", "Error", jOptionPane1.ERROR_MESSAGE);
        return; // Exit the method if any field is empty
        }

        String creditText = txtCredit.getText();
        double Credit = 0.0;
        if (!creditText.isEmpty()) {
            try {
                Credit = Double.parseDouble(creditText);
            } catch (NumberFormatException e) {

                e.printStackTrace(); 

                Credit = 0.0; 
            }
        }

        // Set the values
        Register.setCustomerID(id);
        Register.setCustomerName(Name);
        Register.setCustomerContact(Contact);
        Register.setCustomerPassword(Password);
        Register.setCustomerCredit(Credit);

        // Display
        jOptionPane1.showMessageDialog(Admin_function.this, Register.toString());
        // write text to file
        writeToTextFile(id,Name,Contact,Password,Credit);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtContact1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContact1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContact1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String id1 = txtID1.getText();
        String Name1 = txtName1.getText();
        String Contact1 = txtContact1.getText();
        String Password1 = txtPassword1.getText();
        

        if (id1.isEmpty() || Name1.isEmpty() || Contact1.isEmpty() || Password1.isEmpty()) {
        jOptionPane1.showMessageDialog(Admin_function.this, "Please fill in all fields.", "Error", jOptionPane1.ERROR_MESSAGE);
        return; 
        }

        Register1.setVendorID(id1);
        Register1.setVendorName(Name1);
        Register1.setVendorContact(Contact1);
        Register1.setVendorPassword(Password1);

        //Display
        jOptionPane2.showMessageDialog(Admin_function.this, Register1.toString());
        //write text to file
        writeToTextFile1(id1,Name1,Contact1,Password1);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        dispose();
        TopUpCredit tuc;
        tuc = new TopUpCredit();
        tuc.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = jTable2.getSelectedRow();

        if (selectedRowIndex == -1) {
            jOptionPane1.showMessageDialog(Admin_function.this, "Please select a row to delete.");
            return;
        }

        // Confirm with the user before deleting
        int dialogResult = jOptionPane1.showConfirmDialog(Admin_function.this, "Are you sure you want to delete this customer?", "Confirm Delete", jOptionPane1.YES_NO_OPTION);

        if (dialogResult != jOptionPane1.YES_OPTION) {
            // User canceled the delete operation
            return;
        }

        // Remove the selected row from the table model
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.removeRow(selectedRowIndex);

        // Read the existing content of the file
        ArrayList<String> lines = new ArrayList<>();
        try (BufferedReader br = new BufferedReader(new FileReader("CustomerData.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                lines.add(line);
            }
        } catch (IOException e) {
            e.printStackTrace();
            jOptionPane1.showMessageDialog(Admin_function.this, "Error reading from file: " + e.getMessage(), "Error", jOptionPane1.ERROR_MESSAGE);
            return;
        }

        // Remove the selected row's data from the list
        lines.remove(selectedRowIndex);

        // Write the modified content back to the file
        try (BufferedWriter bw = new BufferedWriter(new FileWriter("CustomerData.txt"))) {
            for (String line : lines) {
                bw.write(line);
                bw.newLine();
            }
            jOptionPane1.showMessageDialog(Admin_function.this, "Customer deleted successfully!");
        } catch (IOException e) {
            e.printStackTrace();
            jOptionPane1.showMessageDialog(Admin_function.this, "Error writing to file: " + e.getMessage(), "Error", jOptionPane1.ERROR_MESSAGE);
        }

        // Clear text fields after deleting
        clearTextFields();       
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = jTable1.getSelectedRow();

        if (selectedRowIndex == -1) {
            jOptionPane1.showMessageDialog(Admin_function.this, "Please select a row to delete.");
            return;
        }

        // Confirm with the user before deleting
        int dialogResult = jOptionPane1.showConfirmDialog(Admin_function.this, "Are you sure you want to delete this vendor?", "Confirm Delete", jOptionPane1.YES_NO_OPTION);

        if (dialogResult != jOptionPane1.YES_OPTION) {
            // User canceled the delete operation
            return;
        }

        // Remove the selected row from the table model
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.removeRow(selectedRowIndex);

        // Read the existing content of the file
        ArrayList<String> lines = new ArrayList<>();
        try (BufferedReader br = new BufferedReader(new FileReader("Vendor.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                lines.add(line);
            }
        } catch (IOException e) {
            e.printStackTrace();
            jOptionPane1.showMessageDialog(Admin_function.this, "Error reading from file: " + e.getMessage(), "Error", jOptionPane1.ERROR_MESSAGE);
            return;
        }

        // Remove the selected row's data from the list
        lines.remove(selectedRowIndex);

        // Write the modified content back to the file
        try (BufferedWriter bw = new BufferedWriter(new FileWriter("Vendor.txt"))) {
            for (String line : lines) {
                bw.write(line);
                bw.newLine();
            }
            jOptionPane1.showMessageDialog(Admin_function.this, "Vendor deleted successfully!");
        } catch (IOException e) {
            e.printStackTrace();
            jOptionPane1.showMessageDialog(Admin_function.this, "Error writing to file: " + e.getMessage(), "Error", jOptionPane1.ERROR_MESSAGE);
        }

        // Clear text fields after deleting
        clearTextFields();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String id4 = txtID4.getText();
        String Name4 = txtName4.getText();
        String Contact4 = txtContact4.getText();
        String Password4 = txtPassword4.getText();
        
        // Check if any text fields is empty
        if (id4.isEmpty() || Name4.isEmpty() || Contact4.isEmpty() || Password4.isEmpty()) {
        jOptionPane2.showMessageDialog(Admin_function.this, "Please fill in all fields.", "Error", jOptionPane1.ERROR_MESSAGE);
        return; // Exit the method if any field is empty
        }

        //set the values
        Register2.setDeliverID(id4);
        Register2.setDeliverName(Name4);
        Register2.setDeliverContact(Contact4);
        Register2.setDeliverPassword(Password4);

        //Display
        jOptionPane2.showMessageDialog(Admin_function.this, Register2.toString());
        //write text to file
        writeToTextFile2(id4,Name4,Contact4,Password4);    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtContact4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContact4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContact4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        displayDeliveryRunnerDataInTable();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel)jTable3.getModel();

        //set data text field when raw
        String name = tblModel.getValueAt(jTable3.getSelectedRow(), 1).toString();
        String contact = tblModel.getValueAt(jTable3.getSelectedRow(), 2).toString();
        String password = tblModel.getValueAt(jTable3.getSelectedRow(), 3).toString();

        //set to textfield
        txtName4.setText(name);
        txtContact4.setText(contact);
        txtPassword4.setText(password);
    }//GEN-LAST:event_jTable3MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = jTable3.getSelectedRow();

        if (selectedRowIndex == -1) {
            jOptionPane1.showMessageDialog(Admin_function.this, "Please select a row to update.");
            return;
        }

        // Get the data from the selected row
        String id = jTable3.getValueAt(selectedRowIndex, 0).toString();
        String newName = txtName4.getText();
        String newContact = txtContact4.getText();
        String newPassword = txtPassword4.getText();

        // Read the existing content of the file
        ArrayList<String> lines = new ArrayList<>();
        try (BufferedReader br = new BufferedReader(new FileReader("DeliveryRunner.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                lines.add(line);
            }
        } catch (IOException e) {
            e.printStackTrace();
            jOptionPane1.showMessageDialog(Admin_function.this, "Error reading from file: " + e.getMessage(), "Error", jOptionPane1.ERROR_MESSAGE);
            return;
        }

        // Update the selected row's data
        String updatedRow = id + "," + newName + "," + newContact + "," + newPassword;
        lines.set(selectedRowIndex, updatedRow);

        // Write the modified content back to the file
        try (BufferedWriter bw = new BufferedWriter(new FileWriter("DeliveryRunner.txt"))) {
            for (String line : lines) {
                bw.write(line);
                bw.newLine();
            }
            jOptionPane1.showMessageDialog(Admin_function.this, "Delivery Runner information updated successfully!");
        } catch (IOException e) {
            e.printStackTrace();
            jOptionPane1.showMessageDialog(Admin_function.this, "Error writing to file: " + e.getMessage(), "Error", jOptionPane1.ERROR_MESSAGE);
        }

        // Clear text fields after updating
        clearTextFields();
        // Refresh the table with updated data
        displayDeliveryRunnerDataInTable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = jTable3.getSelectedRow();

        if (selectedRowIndex == -1) {
            jOptionPane1.showMessageDialog(Admin_function.this, "Please select a row to delete.");
            return;
        }

        // Confirm with the user before deleting
        int dialogResult = jOptionPane1.showConfirmDialog(Admin_function.this, "Are you sure you want to delete this Delivery Runner?", "Confirm Delete", jOptionPane1.YES_NO_OPTION);

        if (dialogResult != jOptionPane1.YES_OPTION) {
            // User canceled the delete operation
            return;
        }

        // Remove the selected row from the table model
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        model.removeRow(selectedRowIndex);

        // Read the existing content of the file
        ArrayList<String> lines = new ArrayList<>();
        try (BufferedReader br = new BufferedReader(new FileReader("DeliveryRunner.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                lines.add(line);
            }
        } catch (IOException e) {
            e.printStackTrace();
            jOptionPane1.showMessageDialog(Admin_function.this, "Error reading from file: " + e.getMessage(), "Error", jOptionPane1.ERROR_MESSAGE);
            return;
        }

        // Remove the selected row's data from the list
        lines.remove(selectedRowIndex);

        // Write the modified content back to the file
        try (BufferedWriter bw = new BufferedWriter(new FileWriter("DeliveryRunner.txt"))) {
            for (String line : lines) {
                bw.write(line);
                bw.newLine();
            }
            jOptionPane1.showMessageDialog(Admin_function.this, "Delivery Runner deleted successfully!");
        } catch (IOException e) {
            e.printStackTrace();
            jOptionPane1.showMessageDialog(Admin_function.this, "Error writing to file: " + e.getMessage(), "Error", jOptionPane1.ERROR_MESSAGE);
        }

        // Clear text fields after deleting
        clearTextFields();    
    }//GEN-LAST:event_jButton10ActionPerformed

    private void btnGoLOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoLOActionPerformed
        dispose();
        Admin_Login al = new Admin_Login();
        al.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnGoLOActionPerformed

    private void btnGoLO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoLO1ActionPerformed
        dispose();
        Admin_Login al = new Admin_Login();
        al.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGoLO1ActionPerformed

    private void btnGoLO2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoLO2ActionPerformed
        dispose();
        Admin_Login al = new Admin_Login();
        al.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGoLO2ActionPerformed

    private void btnGoLO3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoLO3ActionPerformed
        dispose();
        Admin_Login al = new Admin_Login();
        al.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_btnGoLO3ActionPerformed

    private void btnGoLO4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoLO4ActionPerformed
        dispose();
        Admin_Login al = new Admin_Login();
        al.setVisible(true);
        this.setVisible(false);        
    }//GEN-LAST:event_btnGoLO4ActionPerformed
    // write text to file
    private void writeToTextFile(String id, String Name,String Contact, String Password, double Credit){
        try(BufferedReader br = new BufferedReader(new FileReader("CustomerData.txt"))){
            String line;
            while((line = br.readLine()) != null){
            String[] parts = line.split(",\\s*");
            String existingID = parts[0].trim();
            
            //check for duplicate customer ID 
            if(existingID.equals(id)){
                jOptionPane1.showMessageDialog(Admin_function.this,"ID is already registered!");
                return;
            }
        }
        }catch (IOException e){
            // Handle IOException, e.g., display an error message
            e.printStackTrace();
        }
        
        try(BufferedWriter bw = new BufferedWriter(new FileWriter("CustomerData.txt",true))){
            //Append the new registration to the file
            bw.write(id +  "," + Name + "," + Contact + "," + Password + "," + Credit + "\n");
            
            jOptionPane1.showMessageDialog(Admin_function.this, "Register Customer Succesfully!");
        } catch (IOException e) {
            jOptionPane1.showMessageDialog(Admin_function.this,"Register Failed: " + e.getMessage(), "Error",jOptionPane1.ERROR_MESSAGE);
        }
        clearTextFields();
    }
    
    // write text to file
    private void writeToTextFile1(String id1, String Name1,String Contact1, String Password1){
        try(BufferedReader br = new BufferedReader(new FileReader("Vendor.txt"))){
            String line;
            while((line = br.readLine()) != null){
            String[] parts = line.split(",\\s*");
            String existingID = parts[0].trim();
            
            //check for duplicate vendor ID 
            if(existingID.equals(id1)){
                jOptionPane1.showMessageDialog(Admin_function.this,"ID is already registered!");
                return;
            }
            
            
        }
        }catch (IOException e){
            // Handle IOException, e.g., display an error message
            e.printStackTrace();
        }
        
        try(BufferedWriter bw = new BufferedWriter(new FileWriter("Vendor.txt",true))){
            //Append the new registration to the file
            bw.write(id1 +  "," + Name1 + "," + Contact1 + "," + Password1 + "\n");
            
            jOptionPane1.showMessageDialog(Admin_function.this, "Register Vendor Succesfully!");
        } catch (IOException e) {
            jOptionPane1.showMessageDialog(Admin_function.this,"Register Failed: " + e.getMessage(), "Error",jOptionPane1.ERROR_MESSAGE);
        }  
        clearTextFields();
    }
    
    private void writeToTextFile2(String id4, String Name4,String Contact4, String Password4){
        try(BufferedReader br = new BufferedReader(new FileReader("DeliveryRunner.txt"))){
            String line;
            while((line = br.readLine()) != null){
            String[] parts = line.split(",\\s*");
            String existingID = parts[0].trim();
            
            //check for duplicate vendor ID 
            if(existingID.equals(id4)){
                jOptionPane1.showMessageDialog(Admin_function.this,"ID is already registered!");
                return;
            }
            
            
        }
        }catch (IOException e){
            // Handle IOException, e.g., display an error message
            e.printStackTrace();
        }
        
        try(BufferedWriter bw = new BufferedWriter(new FileWriter("DeliveryRunner.txt",true))){
            //Append the new registration to the file
            bw.write(id4 +  "," + Name4 + "," + Contact4 + "," + Password4 + "\n");
            
            jOptionPane1.showMessageDialog(Admin_function.this, "Register Delivery Runner Succesfully!");
        } catch (IOException e) {
            jOptionPane1.showMessageDialog(Admin_function.this,"Register Failed: " + e.getMessage(), "Error",jOptionPane1.ERROR_MESSAGE);
        }  
        clearTextFields();
    }
    
    private void displayVendorDataInTable() {
    
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // Clear existing rows in the table

        try (BufferedReader br = new BufferedReader(new FileReader("Vendor.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] parts = line.split(",\\s*");
                String id = parts[0].trim();
                String name = parts[1].trim();
                String contact = parts[2].trim();
                String password = parts[3].trim();

                // Add a new row to the table
                model.addRow(new Object[]{id, name, contact, password});
            }
        } catch (IOException e) {
            e.printStackTrace();
            // Handle the exception, e.g., show an error message
        }
    }
    
    private void displayCustomerDataInTable() {
    
    DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
    model.setRowCount(0); // Clear existing rows in the table

        try (BufferedReader br = new BufferedReader(new FileReader("CustomerData.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] parts = line.split(",\\s*");
                String id = parts[0].trim();
                String name = parts[1].trim();
                String contact = parts[2].trim();
                String password = parts[3].trim();

                // Add a new row to the table
                model.addRow(new Object[]{id, name, contact, password});
            }
        } catch (IOException e) {
            e.printStackTrace();
            // Handle the exception, e.g., show an error message
        }
    }
    
    private void displayDeliveryRunnerDataInTable() {
    
    DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
    model.setRowCount(0); // Clear existing rows in the table

        try (BufferedReader br = new BufferedReader(new FileReader("DeliveryRunner.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] parts = line.split(",\\s*");
                String id = parts[0].trim();
                String name = parts[1].trim();
                String contact = parts[2].trim();
                String password = parts[3].trim();

                // Add a new row to the table
                model.addRow(new Object[]{id, name, contact, password});
            }
        } catch (IOException e) {
            e.printStackTrace();
            // Handle the exception, e.g., show an error message
        }
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_function.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_function.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_function.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_function.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_function().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoLO;
    private javax.swing.JButton btnGoLO1;
    private javax.swing.JButton btnGoLO2;
    private javax.swing.JButton btnGoLO3;
    private javax.swing.JButton btnGoLO4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JOptionPane jOptionPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtContact1;
    private javax.swing.JTextField txtContact2;
    private javax.swing.JTextField txtContact3;
    private javax.swing.JTextField txtContact4;
    private javax.swing.JTextField txtCredit;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtID1;
    private javax.swing.JTextField txtID4;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtName2;
    private javax.swing.JTextField txtName3;
    private javax.swing.JTextField txtName4;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPassword1;
    private javax.swing.JTextField txtPassword2;
    private javax.swing.JTextField txtPassword3;
    private javax.swing.JTextField txtPassword4;
    // End of variables declaration//GEN-END:variables

    class RegistrationCustomer extends Customer {
        public RegistrationCustomer(String customerID, String customerName, String customerContact, String customerPassword, double customerCredit) {
            super(customerID, customerName, customerContact, customerPassword, customerCredit);
        }
        
        @Override
        public void setCustomerID(String customerID) {
            super.setCustomerID(customerID);
        }
        
        @Override
        public void setCustomerName(String customerName) {
            super.setCustomerName(customerName);
        }
        
        @Override
        public void setCustomerContact(String customerContact) {
            super.setCustomerContact(customerContact);
        }
        
        @Override
        public void setCustomerPassword(String customerPassword) {
            super.setCustomerPassword(customerPassword);    
        }
        
        @Override
        public void setCustomerCredit(double customerCredit){
            super.setCustomerCredit(customerCredit);
        }       
    }
    
    class RegistrationVendor extends Vendor{
        public RegistrationVendor(String vendorID, String vendorName, String vendorContact, String vendorPassword){
            super(vendorID, vendorName, vendorContact, vendorPassword);
        }
        
        @Override
        public void setVendorID(String vendorID){
            super.setVendorID(vendorID);
        }
        
        @Override
        public void setVendorName(String vendorName) {
            super.setVendorName(vendorName);
        }
        
        @Override
        public void setVendorContact(String vendorContact){
            super.setVendorContact(vendorContact);
        }
        
        public void setVendorPassowrd(String vendorPassword){
            super.setVendorPassword(vendorPassword);
        }               
    }
    
    class RegistrationDelivery extends DeliveryRunner{
        public RegistrationDelivery(String deliverID, String deliverName, String deliverContact, String deliverPassword){
            super(deliverID, deliverName, deliverContact, deliverPassword);
        }
        
        @Override
        public void setDeliverID(String deliverID){
            super.setDeliverID(deliverID);
        }
        
        @Override
        public void setDeliverName(String deliverName) {
            super.setDeliverName(deliverName);
        }
        
        @Override
        public void setDeliverContact(String deliverContact){
            super.setDeliverContact(deliverContact);
        }
        
        public void setDeliverPassowrd(String deliverPassword){
            super.setDeliverPassword(deliverPassword);
        }    
    }        
    
    private void clearTextFields(){
    txtID.setText("");
    txtName.setText("");
    txtContact.setText("");
    txtPassword.setText("");
        
    txtID1.setText("");
    txtName1.setText("");
    txtContact1.setText("");
    txtPassword1.setText("");
    
    txtID4.setText("");
    txtName4.setText("");
    txtContact4.setText("");
    txtPassword4.setText("");
    }
}
